// V1 control-plane entity contracts only.
// No transition logic, storage logic, or runtime behavior belongs here.
// Lifecycle ownership is intentionally centralized elsewhere.
// Repositories and services must not infer authority from these contracts alone.

const ENTITY_SCHEMAS = Object.freeze({
  durable_runs: Object.freeze({
    description: 'Persisted bounded durable runtime shell run object linking invocation, proof, supervision, and lineage context.',
    required: Object.freeze({
      durable_run_id: 'string; unique durable run identifier',
      parent_task_id: 'string; parent task identifier serving as the run anchor',
      root_task_id: 'string; root lineage task identifier for the run',
      run_status: 'string; bounded durable run status, open or closed in v1',
      invocation_name: 'string; bounded operator invocation contract name',
      scenario_name: 'string; bounded governed scenario name',
      supervision_enabled: 'boolean; whether bounded supervision linkage is enabled for this run',
      opened_at: 'string; ISO timestamp when the durable run was opened',
      created_at: 'string; ISO timestamp when the durable run record was created',
      updated_at: 'string; ISO timestamp when the durable run record was last updated',
    }),
    optional: Object.freeze({
      closed_at: 'string|null; ISO timestamp when the durable run was closed',
      approved_spawn_request_id: 'string|null; approved spawn request linked to the run',
      approved_approval_request_id: 'string|null; approval request that approved the run child spawn',
      child_task_id: 'string|null; governed child task linked to the run',
      denied_spawn_request_id: 'string|null; denied spawn request linked to the walkthrough run',
      denied_approval_request_id: 'string|null; denied approval request linked to the walkthrough run',
      proof_summary_json: 'object|null; bounded proof summary snapshot for operator/runtime inspection',
      last_control_action: 'string|null; most recent bounded operator control action observed for this run',
      last_control_at: 'string|null; ISO timestamp of most recent bounded operator control action',
    }),
  }),

  tasks: Object.freeze({
    description: 'Durable task record for root and child tasks in the v1 control plane.',
    required: Object.freeze({
      task_id: 'string; unique durable task identifier',
      root_task_id: 'string; root task identifier for the entire lineage tree, equals task_id for root tasks',
      task_kind: 'string; bounded task kind identifier',
      status: 'string; must align with TASK_STATES vocabulary',
      priority: 'string|number; scheduler-facing priority value',
      task_scope_json: 'object; bounded task scope payload that constrains execution intent',
      input_payload_json: 'object; input payload for task execution',
      spawn_depth: 'number; lineage depth for this task, root task is 0, child task is 1 in v1',
      active_child_count: 'number; count of currently active child tasks spawned by this task, capped by policy in v1',
      spawn_budget_used: 'number; running count of spawn budget consumed by this task',
      spawn_budget_limit: 'number; max allowed spawn budget for this task under v1 policy',
      retry_count: 'number; current retry count consumed by this task',
      max_retries: 'number; max retries allowed for this task',
      checkpoint_seq: 'number; latest checkpoint sequence observed for this task',
      created_at: 'string; ISO timestamp when the task record was created',
      updated_at: 'string; ISO timestamp when the task record was last updated',
    }),
    optional: Object.freeze({
      parent_task_id: 'string|null; immediate parent task identifier, null for root tasks',
      created_by_agent_id: 'string|null; agent that created the task, null when system/operator created it directly',
      assigned_agent_id: 'string|null; currently assigned agent instance identifier',
      lease_owner: 'string|null; current lease owner token or worker identity',
      lease_expires_at: 'string|null; ISO timestamp when the current lease expires',
      heartbeat_at: 'string|null; ISO timestamp of the last accepted heartbeat for this task',
      result_payload_json: 'object|null; bounded result payload produced on successful completion',
      error_code: 'string|null; normalized failure code for terminal or retryable failures',
      error_message: 'string|null; normalized failure summary text',
      wait_reason: 'string|null; explicit wait reason such as waiting_for_approval or waiting_for_child',
      blocked_on_spawn_request_id: 'string|null; spawn request causing current wait state',
      blocked_on_approval_request_id: 'string|null; approval request causing current wait state',
      blocked_on_task_id: 'string|null; task dependency currently blocking this task',
      started_at: 'string|null; ISO timestamp when execution started',
      completed_at: 'string|null; ISO timestamp when task completed successfully',
      failed_at: 'string|null; ISO timestamp when task entered failed terminal state',
      cancelled_at: 'string|null; ISO timestamp when task entered cancelled terminal state',
    }),
  }),

  task_events: Object.freeze({
    description: 'Append-only task-scoped event stream for task lifecycle and executor-visible milestones.',
    required: Object.freeze({
      event_id: 'string; unique durable event identifier',
      task_id: 'string; task this event belongs to',
      event_type: 'string; event vocabulary value, task-oriented subset of audit/task events',
      event_payload_json: 'object; structured event payload',
      created_at: 'string; ISO timestamp when the event was recorded',
    }),
    optional: Object.freeze({
      agent_id: 'string|null; agent associated with this task event when applicable',
      idempotency_key: 'string|null; dedupe key for safely repeated event writes',
    }),
  }),

  agent_templates: Object.freeze({
    description: 'Approved template registry record for agent instantiation policy. V1 expects exactly one enabled ephemeral child template.',
    required: Object.freeze({
      agent_template_id: 'string; unique approved template identifier',
      version: 'string|number; template version identifier',
      template_name: 'string; human-readable template name',
      agent_class: 'string; approved agent class name tied to this template',
      agent_kind: 'string; v1 expects ephemeral_child for the single approved template',
      allowed_task_kinds_json: 'array; task kinds this template may be used for',
      capabilities_json: 'array|object; bounded capability declaration for this template',
      forbidden_capabilities_json: 'array|object; explicitly forbidden capability set for this template',
      policy_boundary_class: 'string; policy boundary classification for governance checks',
      spawn_requires_approval: 'boolean; must be true in v1',
      max_recursion_depth: 'number; max allowed depth for tasks/agents created from this template, 1 in v1',
      max_active_children_per_parent: 'number; max active child count allowed per parent, 1 in v1',
      ttl_seconds: 'number; retirement time-to-live for temporary child agents',
      enabled: 'boolean; whether this template may be selected for new spawn requests',
      created_at: 'string; ISO timestamp when the template was registered',
      updated_at: 'string; ISO timestamp when the template was last updated',
    }),
    optional: Object.freeze({}),
  }),

  spawn_requests: Object.freeze({
    description: 'Governed request to create one child task and one ephemeral child agent from an approved template.',
    required: Object.freeze({
      spawn_request_id: 'string; unique durable spawn request identifier',
      parent_task_id: 'string; task requesting the child spawn',
      root_task_id: 'string; root lineage task identifier inherited from the parent task',
      child_task_kind: 'string; proposed child task kind',
      child_task_scope_json: 'object; bounded child task scope used for dedupe and later execution constraints',
      agent_template_id: 'string; approved template identifier selected for this request',
      agent_template_version: 'string|number; template version pinned by this request',
      status: 'string; must align with SPAWN_REQUEST_STATES vocabulary',
      spawn_intent_hash: 'string; deterministic dedupe hash for equivalent spawn intent',
      requested_by: 'string; actor identity or subsystem that created the request',
      creation_reason: 'string; normalized reason for requesting a child spawn',
      justification: 'string; human-readable governance justification for the request',
      approval_required: 'boolean; must be true in v1',
      created_at: 'string; ISO timestamp when the spawn request was created',
      updated_at: 'string; ISO timestamp when the spawn request was last updated',
    }),
    optional: Object.freeze({
      parent_agent_id: 'string|null; agent associated with the parent task when applicable',
      approval_request_id: 'string|null; linked approval request record for governance decisioning',
      idempotency_key: 'string|null; caller-supplied idempotency key for repeated propose calls',
      approved_by: 'string|null; operator identity that approved the request',
      approved_at: 'string|null; ISO timestamp of approval',
      denied_by: 'string|null; operator identity that denied the request',
      denied_at: 'string|null; ISO timestamp of denial',
      deny_reason: 'string|null; structured or normalized denial reason',
      instantiated_agent_id: 'string|null; resulting child agent instance identifier',
      instantiated_task_id: 'string|null; resulting child task identifier',
      duplicate_of_spawn_request_id: 'string|null; canonical request identifier when this request is duplicate-suppressed',
      expires_at: 'string|null; ISO timestamp when pending approval/request validity expires',
    }),
  }),

  approval_requests: Object.freeze({
    description: 'Explicit operator approval record linked to a governed action. V1 uses this for spawn approvals only.',
    required: Object.freeze({
      approval_request_id: 'string; unique durable approval request identifier',
      approval_kind: 'string; kind of approval target, spawn_request in v1',
      target_id: 'string; durable identifier of the governed target entity',
      status: 'string; must align with APPROVAL_STATES vocabulary',
      requested_at: 'string; ISO timestamp when approval was requested',
      requested_by: 'string; actor identity or subsystem requesting approval',
      reason: 'string; human-readable reason presented to operator',
    }),
    optional: Object.freeze({
      decision_by: 'string|null; operator identity that made the decision',
      decision_at: 'string|null; ISO timestamp of decision',
      decision_reason: 'string|null; rationale recorded for approval/denial/cancellation',
      expires_at: 'string|null; ISO timestamp when this approval request expires if unanswered',
    }),
  }),

  agent_registry: Object.freeze({
    description: 'Registry of instantiated agent instances. V1 includes ephemeral child agents only, not pooled or persistent agents.',
    required: Object.freeze({
      agent_id: 'string; unique durable agent instance identifier',
      agent_class: 'string; approved agent class name',
      agent_template_id: 'string; template identifier this instance was created from',
      agent_template_version: 'string|number; template version pinned for this instance',
      agent_kind: 'string; v1 expects ephemeral_child',
      spawned_by_spawn_request_id: 'string; spawn request that authorized this agent instance',
      root_task_id: 'string; root lineage task identifier',
      task_scope_json: 'object; bounded execution scope for this agent instance',
      capabilities_json: 'array|object; capability declaration realized for this instance',
      policy_boundary_class: 'string; policy boundary classification inherited from template/governance rules',
      status: 'string; must align with AGENT_STATES vocabulary',
      approval_state: 'string; approval status snapshot for this instance lifecycle context',
      spawn_depth: 'number; lineage depth for this agent instance, 1 for child agents in v1',
      child_count: 'number; count of children created by this agent, must remain 0 in v1',
      ttl_seconds: 'number; retirement TTL for this temporary agent',
      creation_reason: 'string; normalized creation reason inherited from spawn request',
      created_at: 'string; ISO timestamp when the agent instance was created',
      updated_at: 'string; ISO timestamp when the agent instance was last updated',
    }),
    optional: Object.freeze({
      parent_agent_id: 'string|null; parent agent instance identifier, null when parent is operator/system rooted',
      spawned_by_task_id: 'string|null; task that directly caused this agent to be instantiated',
      current_task_id: 'string|null; currently assigned task identifier',
      lease_owner: 'string|null; current lease owner token or worker identity',
      lease_expires_at: 'string|null; ISO timestamp when current agent lease expires',
      heartbeat_at: 'string|null; ISO timestamp of last accepted agent heartbeat',
      retire_at: 'string|null; ISO timestamp when the agent should be force-retired by TTL policy',
      activated_at: 'string|null; ISO timestamp when the agent first became active',
      retired_at: 'string|null; ISO timestamp when the agent entered terminal retired state',
      last_checkpoint_id: 'string|null; latest checkpoint associated with this agent or its current task',
      last_error_code: 'string|null; latest normalized failure code seen for this agent',
      last_error_message: 'string|null; latest failure summary seen for this agent',
    }),
  }),

  checkpoints: Object.freeze({
    description: 'Durable checkpoint records for resumable task or child execution progress.',
    required: Object.freeze({
      checkpoint_id: 'string; unique durable checkpoint identifier',
      task_id: 'string; task the checkpoint belongs to',
      checkpoint_seq: 'number; monotonically increasing checkpoint sequence for the task',
      checkpoint_kind: 'string; normalized checkpoint type identifier',
      checkpoint_payload_json: 'object; resumable checkpoint payload',
      created_at: 'string; ISO timestamp when the checkpoint was recorded',
      created_by: 'string; actor identity or subsystem that wrote the checkpoint',
      is_latest: 'boolean; whether this row is the latest checkpoint for the task at write time',
    }),
    optional: Object.freeze({
      agent_id: 'string|null; agent associated with the checkpoint when applicable',
    }),
  }),

  audit_events: Object.freeze({
    description: 'Append-only control-plane audit log covering task, spawn, approval, agent, checkpoint, and safety events.',
    required: Object.freeze({
      audit_event_id: 'string; unique durable audit event identifier',
      entity_type: 'string; entity family such as task, agent, spawn_request, approval_request, checkpoint',
      entity_id: 'string; durable identifier of the primary entity being audited',
      event_type: 'string; must align with AUDIT_EVENT_TYPES vocabulary',
      event_payload_json: 'object; structured audit payload',
      actor_type: 'string; actor family such as system, operator, agent, worker',
      actor_id: 'string; durable identifier or normalized actor label',
      created_at: 'string; ISO timestamp when the audit event was recorded',
    }),
    optional: Object.freeze({
      related_task_id: 'string|null; related task identifier for correlation',
      related_agent_id: 'string|null; related agent identifier for correlation',
      related_spawn_request_id: 'string|null; related spawn request identifier for correlation',
      related_approval_request_id: 'string|null; related approval request identifier for correlation',
      idempotency_key: 'string|null; dedupe key for safely repeated audit writes',
    }),
  }),
});

module.exports = {
  ENTITY_SCHEMAS,
};
