name: Unity Generate ALF

on:
  workflow_dispatch:

jobs:
  generate-alf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Unity ALF request file
        uses: game-ci/unity-request-activation-file@v2
        id: alf
        with:
          unityVersion: 2022.3.62f1

      - name: Upload ALF artifact
        uses: actions/upload-artifact@v4
        with:
          name: unity-alf
          path: ${{ steps.alf.outputs.activationFilePath }}
